# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-2"

  # Only these AWS Account IDs may be operated on by this template
  allowed_account_ids = ["470363915259"]
}
