# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    region         = "us-west-1"
    bucket         = "codeforcalifornia"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "terragrunt-states/non-prod/us-east-2/stage/alb/terraform.tfstate"
  }
}
