# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "codeforsanjose-terraform"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "terragrunt-states/./terraform.tfstate"
    region         = "us-west-1"
  }
}
